source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Fusuma_Example', :exclusive => true do
  pod 'Fusuma', :path => '../'
end

target 'Fusuma_Tests', :exclusive => true do
  pod 'Fusuma', :path => '../'
end
